_core:
  default_config_hash: ijfbzDTN4CbE7Sr-6ubWzy_t1vH4OtU1doNCLssVz-4
langcode: sv
uuid: f12a6702-2cb0-41cc-804f-1e9cbb3c8afa
name: 'TritonLed Sverige'
mail: info@tritonled.se
slogan: 'Fråga oss om belysning'
page:
  403: ''
  404: ''
  front: /page/1
admin_compact_mode: false
weight_select_max: 100
default_langcode: sv
mail_notification: null
